title: Kelly Ferrone
description: My personal site to show off what I'm all about. 
show_downloads: false
google_analytics: UA-127861278-1
google_tag_manager: GTM-MVFWXX9
theme: jekyll-theme-minimal
repository: kferrone/kferrone.github.io
domain: www.kellyferrone.com
collections_dir: collections
logo: /assets/img/logo.png
internal_properties: 
  - ext
  - path
  - relative_path
  - previous
  - next
  - output
  - content
  - url
  - collection
  - excerpt
collections:
  - components
  - views
  - lib
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jemoji
exclude: [
  'vendor',
  'script',
  '*.gemspec',
  'Gemfile*',
  '.project',
  '*.http',
  'docs',
  'README.md',
  'LICENSE',
  'codealike.json',
  '.DS_Store'
]
