title: Kelly Ferrone
description: My personal site to show off what I'm all about. 
show_downloads: false
google_analytics: UA-127861278-1
google_tag_manager: GTM-MVFWXX9
theme: jekyll-theme-minimal
repository: kferrone/kferrone.github.io
domain: www.kellyferrone.com
collections_dir: collections
logo: /assets/img/logo.png

# this is all of the third party libraries using unpkg.com as the cdn
js:
  repo: https://unpkg.com
  dependencies:
    
    # useful utilities
    - id: lodash
      version: 4.17.11
      env:
        prod: 
          file: lodash.min.js
          integrity: sha384-2HWZ0KJxkQ3nhRpHPzk4AO2iIy1S8rSGwN5MpMS/xf34mqOahLqEbqwvdk48EnEv
    
    # Just in case you need to make your own HTML
    - id: '@webcomponents/webcomponentsjs'
      version: 2.1.3
      env:
        prod: 
          file: webcomponents-bundle.js
          integrity: sha384-HsZ+MKDOTqEf8EqIiqCFzVs9/++MFAa4Scd0wUbijRkD3U0z8TRS4IuO4+zSbiTw
    
    # lightweight and dead simple implementation of WebcomponentsJS
    - id: hybrids
      version: 1.4.2
      env:
        prod: 
          file: dist/hybrids.js
          integrity: sha384-mge9Ex93YlXz5SXtg9xgn1qewm3CN5SXOPyPxzXxuVOAhLEITMijr3llE68YvurI
    
    # component builder library magical extravaganza
    - id: vue
      version: 2.5.17
      env: 
        prod: 
          file: dist/vue.min.js
          integrity: sha384-9MzmvphdUvLZJKasjD7VqYE4SqffhZDOwDTMyokP2tx+fjBo59ljvrlgUAaaME44
        dev: 
          file: dist/vue.js
          integrity: sha384-vGq6VlJ/rGDK5hwCZhgtrb5j4nOanwgWgBSe9anrJGQHqCgkBo45u6lAxlVR0U+Q
    
    # SPA style routing using a hastag ######
    - id: vue-router
      version: 3.0.1
      env: 
        prod: 
          file: dist/vue-router.min.js
          integrity: sha384-g4QZ3CgAtAdAvMxrn/IlcxAxZxqs+hDd0fcj0GMX8Qf3IfjXu0VBHY8d3sq0UCRV
        dev: 
          file: dist/vue-router.js
          integrity: sha384-MxZ2oEVMAOeaFTT5bvHSNf/+FE3FhImgoA6P77hnpETkq/M0hyTJUaA/QQzEWCHe
    
    #lightweight AJAX with Promises, pairs well with VueJS
    - id: axios
      version: 0.18.0
      env:
        prod: 
          file: dist/axios.min.js
          integrity: sha384-U/+EF1mNzvy5eahP9DeB32duTkAmXrePwnRWtuSh1C/bHHhyR1KZCr/aGZBkctpY
        dev: 
          file: dist/axios.js
          integrity: sha384-i1spcL1noifN1wFk9Li9LLBO5DJoBKQCNeSsSBDyrhbZayRb2Z1NIm9jImiTJn9I

internal_properties: 
  - ext
  - path
  - relative_path
  - previous
  - next
  - output
  - content
  - url
  - collection
  - excerpt
collections:
  - components
  - views
  - lib
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jemoji
exclude: [
  'vendor',
  'script',
  '*.gemspec',
  'Gemfile*',
  '.project',
  '*.http',
  'docs',
  'README.md',
  'LICENSE',
  'codealike.json',
  '.DS_Store'
]
