title: Kelly Ferrone
description: My personal site to show off what I'm all about.  
show_downloads: false
theme: jekyll-theme-minimal
style: main
github_username: kferrone
repository: kferrone/kferrone.github.io
domain: www.kellyferrone.com
collections_dir: collections
logo: /assets/img/logo.png

addons:

  google_analytics: 
    id: UA-127861278-1
    enabled: true

  google_tag_manager: 
    id: GTM-MVFWXX9
    enabled: false

  google_adsense:
    id: ca-pub-6922931690128889
    enabled: true

  google_optimize:
    id: GTM-MRK4GKZ
    enabled: true

  blogger:
    id: '3240227952105036963'
    url: blog.kellyferrone.com
    key: 'AIzaSyDjJNQ9UsIHdYaeAM02LGMo1LFplKzDddU'
    #key: 'AIzaSyAHcSA1ZNS57kjqT-7CF1OSANb8C5PF0Z8'
    enabled: true

  hubspot: 
    id: 3962794
    enabled: false
  
  hotjar: 
    id: 1102279
    enabled: true

  pinterest:
    id: 5dae44c4b9f518f2c932edfd320bd141
    enabled: true

# this is all of the third party libraries using unpkg.com as the cdn
dependencies:
  repo: https://unpkg.com
  css:

    #dead simple css theme
    - id: purecss
      version: 1.0.0
      env:
        prod: 
          file: build/pure-min.css
          integrity: sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w

    - id: purecss
      version: 1.0.0
      env:
        prod: 
          file: build/grids-responsive-min.css
          integrity: sha384-b92sF+wDNTHrfEtRaYo+EpcA8FUyHOSXrdxKc9XB9kaaX1rSQAgMevW6cYeE5Bdv

  js:
    
    # useful utilities
    - id: lodash
      version: 4.17.11
      env:
        prod: 
          file: lodash.min.js
          integrity: sha384-2HWZ0KJxkQ3nhRpHPzk4AO2iIy1S8rSGwN5MpMS/xf34mqOahLqEbqwvdk48EnEv

    # get yo dates on
    - id: moment
      version: 2.22.2
      env:
        prod:
          file: min/moment.min.js
          integrity: sha384-sIzeKWIAHvT0Vm8QbfLCqZwBG0WMCkWVAOYd/330YSNeeQ1Y57N3T9lQz5Ry/EHH
        dev:
          file: moment.js
          integrity: sha384-rCWDlX0ts8DR19RqjyA5Pi/rsyO1CtL0u3FwkCX9+shkYbnKVIkXceW5FARgCH6T
    
    # Just in case you need to make your own HTML
    - id: '@webcomponents/webcomponentsjs'
      version: 2.1.3
      env:
        prod: 
          file: webcomponents-bundle.js
          integrity: sha384-HsZ+MKDOTqEf8EqIiqCFzVs9/++MFAa4Scd0wUbijRkD3U0z8TRS4IuO4+zSbiTw
    
    # lightweight and dead simple implementation of WebcomponentsJS
    - id: hybrids
      version: 1.4.2
      env:
        prod: 
          file: dist/hybrids.js
          integrity: sha384-mge9Ex93YlXz5SXtg9xgn1qewm3CN5SXOPyPxzXxuVOAhLEITMijr3llE68YvurI
    
    # component builder library magical extravaganza
    - id: vue
      version: 2.5.17
      env: 
        prod: 
          file: dist/vue.min.js
          integrity: sha384-9MzmvphdUvLZJKasjD7VqYE4SqffhZDOwDTMyokP2tx+fjBo59ljvrlgUAaaME44
        dev: 
          file: dist/vue.js
          integrity: sha384-vGq6VlJ/rGDK5hwCZhgtrb5j4nOanwgWgBSe9anrJGQHqCgkBo45u6lAxlVR0U+Q
    
    # SPA style routing using a hastag ######
    - id: vue-router
      version: 3.0.1
      env: 
        prod: 
          file: dist/vue-router.min.js
          integrity: sha384-g4QZ3CgAtAdAvMxrn/IlcxAxZxqs+hDd0fcj0GMX8Qf3IfjXu0VBHY8d3sq0UCRV
        dev: 
          file: dist/vue-router.js
          integrity: sha384-MxZ2oEVMAOeaFTT5bvHSNf/+FE3FhImgoA6P77hnpETkq/M0hyTJUaA/QQzEWCHe
    
    #lightweight AJAX with Promises, pairs well with VueJS
    - id: axios
      version: 0.18.0
      env:
        prod: 
          file: dist/axios.min.js
          integrity: sha384-U/+EF1mNzvy5eahP9DeB32duTkAmXrePwnRWtuSh1C/bHHhyR1KZCr/aGZBkctpY
        dev: 
          file: dist/axios.js
          integrity: sha384-i1spcL1noifN1wFk9Li9LLBO5DJoBKQCNeSsSBDyrhbZayRb2Z1NIm9jImiTJn9I

internal_properties: 
  - ext
  - path
  - relative_path
  - previous
  - next
  - output
  - content
  - url
  - collection
collections:
  - components
  - views
  - lib
  - styles
  - blogger
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jemoji
exclude: [
  'vendor',
  'script',
  '*.gemspec',
  'Gemfile*',
  '.project',
  '*.http',
  'docs',
  'README.md',
  'LICENSE',
  'codealike.json',
  '.DS_Store',
  'wiki'
]
