title: Kelly Ferrone
description: My personal site to show off what I'm all about. 
show_downloads: false
google_analytics: UA-127861278-3
theme: jekyll-theme-cayman
repository: kferrone/kferrone.github.io
domain: github.kellyferrone.com
collections_dir: collections
collections:
  - components
  - views
  - lib
plugins:
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
exclude: [
  'vendor',
  'script',
  '*.gemspec',
  'Gemfile*',
  '.project',
  '*.http',
  'docs',
  'README.md',
  'LICENSE',
  'codealike.json',
  '.DS_Store'
]